# Generated by Django 3.2.4 on 2021-06-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='sample',
            field=models.CharField(default='', max_length=100),
        ),
    ]
